# Generated by Django 4.2.6 on 2023-10-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('Category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.category')),
            ],
        ),
    ]
